sudo: required
services:
  - docker

before_install:
  - docker build -t davidemmerich/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true davidemmerich/react-test npm test

after_success:
  - docker build -t davidemmerich/multi-frontend ./frontend
  - docker build -t davidemmerich/multi-proxy ./proxy
  - docker build -t davidemmerich/multi-api ./api
  - docker build -t davidemmerich/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push davidemmerich/multi-frontend
  - docker push davidemmerich/multi-proxy
  - docker push davidemmerich/multi-api
  - docer push davidemmerich/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: elasticbeanstalk-us-east-2-653447405869
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
