version: "3"
services:
  proxy:
    restart: unless-stopped
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api
  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./frontend:/home/node/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./api:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=25Jul03008800
      - PG_PORT=5432
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=25Jul03008800
  redis:
    image: redis:latest
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./worker:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
